[project]
name = "appsec-ghas"
version = "0.1.0"
description = "Application Security benchmark repository for GHAS"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.4",
]
